// AUTO-GENERATED by scripts/calibrate.ts
// N=10000, seed=7777
// 各軸の "ランダム回答時の平均/標準偏差" を保存。z-score 化に使う。

export const BASELINE_MEAN: Readonly<Record<string, number>> = {
  attractE: 4.78,
  attractF: 6.64,
  attractI: 6.16,
  attractJ: 4.75,
  attractN: 6.20,
  attractP: 4.68,
  attractS: 6.44,
  attractT: 5.94,
  awkwardness: 7.21,
  caretakerDependency: 6.30,
  conversationDensity: 4.62,
  dailyLifeFeel: 7.65,
  distanceSense: 7.45,
  edginessTolerance: 3.65,
  emotionalInstabilityTolerance: 2.12,
  humanity: 12.05,
  independence: 9.64,
  innocenceTolerance: 5.01,
  lateNightVibe: 5.50,
  lineTemperature: 5.66,
  loveExpression: 8.73,
  lowTempEmotion: 12.26,
  neglectTolerance: 1.41,
  saveDesire: 3.71,
  silenceDependency: 8.35,
  understandDesire: 11.71,
  urbanSense: 5.82,
  vibeMatch: 5.40,
}

export const BASELINE_STD: Readonly<Record<string, number>> = {
  attractE: 2.97,
  attractF: 3.05,
  attractI: 3.07,
  attractJ: 3.17,
  attractN: 3.01,
  attractP: 2.99,
  attractS: 3.08,
  attractT: 3.01,
  awkwardness: 2.47,
  caretakerDependency: 3.46,
  conversationDensity: 2.42,
  dailyLifeFeel: 3.96,
  distanceSense: 2.36,
  edginessTolerance: 1.98,
  emotionalInstabilityTolerance: 1.57,
  humanity: 3.42,
  independence: 4.33,
  innocenceTolerance: 2.03,
  lateNightVibe: 2.83,
  lineTemperature: 2.77,
  loveExpression: 3.55,
  lowTempEmotion: 4.00,
  neglectTolerance: 1.37,
  saveDesire: 2.25,
  silenceDependency: 3.12,
  understandDesire: 3.96,
  urbanSense: 2.32,
  vibeMatch: 2.94,
}

// score を z-score 化（baseline 想定からの偏差）
export function zScore(axis: string, raw: number): number {
  const m = BASELINE_MEAN[axis] ?? 0
  const s = BASELINE_STD[axis] ?? 1
  return (raw - m) / s
}

// 標準正規分布の CDF 近似（Abramowitz-Stegun）。z-score → 累積確率（0..1）。
function normalCdf(z: number): number {
  const sign = z < 0 ? -1 : 1
  const x = Math.abs(z) / Math.SQRT2
  const t = 1 / (1 + 0.3275911 * x)
  const y =
    1 -
    ((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t +
      0.254829592) *
      t *
      Math.exp(-x * x)
  return 0.5 * (1 + sign * y)
}

// raw score → 「上位何%」（1..99）。z>0 で上位（小さい数字）、z<0 で下位（大きい数字）
export function topPercentile(axis: string, raw: number): number {
  const z = zScore(axis, raw)
  const p = normalCdf(z) // 累積確率（小=低スコア、大=高スコア）
  const topPct = Math.round((1 - p) * 100)
  return Math.min(99, Math.max(1, topPct))
}

// 全 personality 軸（attract/self/other 系を除く）から最も極端（|z| 大）な top N を返す。
// 結果ページの「あなたの最希少ポイント」用。
const PERSONALITY_AXES: readonly string[] = [
  "lowTempEmotion",
  "lateNightVibe",
  "urbanSense",
  "dailyLifeFeel",
  "awkwardness",
  "neglectTolerance",
  "loveExpression",
  "lineTemperature",
  "humanity",
  "emotionalInstabilityTolerance",
  "silenceDependency",
  "innocenceTolerance",
  "conversationDensity",
  "distanceSense",
  "independence",
  "vibeMatch",
  "edginessTolerance",
  "caretakerDependency",
  "understandDesire",
  "saveDesire",
]

export interface RarityHighlight {
  readonly axis: string
  readonly z: number
  readonly topPercent: number // 1..99
  readonly direction: "high" | "low"
}

export function getRarityHighlights(
  scores: Readonly<Record<string, number>>,
  count: number = 3
): readonly RarityHighlight[] {
  return PERSONALITY_AXES.map((axis) => {
    const raw = scores[axis] ?? 0
    const z = zScore(axis, raw)
    return {
      axis,
      z,
      topPercent: topPercentile(axis, raw),
      direction: z >= 0 ? ("high" as const) : ("low" as const),
    }
  })
    .sort((a, b) => Math.abs(b.z) - Math.abs(a.z))
    .slice(0, count)
}

// 各 personality 軸の "ユニーク度" 係数。
// 他軸と同時加点される頻度が高い（= 信号が重複してる）軸ほど低い値。
// scoreMbti / 各種マッチングで重みに掛けて、二重カウントを抑制する。
export const AXIS_UNIQUENESS: Readonly<Record<string, number>> = {
  awkwardness: 0.534,
  caretakerDependency: 0.526,
  conversationDensity: 0.538,
  dailyLifeFeel: 0.533,
  distanceSense: 0.532,
  edginessTolerance: 0.537,
  emotionalInstabilityTolerance: 0.546,
  humanity: 0.530,
  independence: 0.539,
  innocenceTolerance: 0.540,
  lateNightVibe: 0.551,
  lineTemperature: 0.534,
  loveExpression: 0.529,
  lowTempEmotion: 0.537,
  neglectTolerance: 0.532,
  saveDesire: 0.521,
  silenceDependency: 0.536,
  understandDesire: 0.533,
  urbanSense: 0.552,
  vibeMatch: 0.544,
}

// 軸の "独立な信号としての重み"。MBTI 次元軸（attract系）は 1.0、
// personality 軸は AXIS_UNIQUENESS をそのまま使う。
export function axisUniqueness(axis: string): number {
  if (axis.startsWith("attract")) return 1.0
  return AXIS_UNIQUENESS[axis] ?? 1.0
}

// 各 MBTI profile の "ランダム回答時の scoreMbti 分布" の mean / std。
// 高相関軸で構成された profile は std が大きくなり、勝率が偏る。
// scoreMbti の最後で (raw - mean) / std を取って per-profile に正規化する。
export const PROFILE_BASELINE_MEAN: Readonly<Record<string, number>> = {
  INFP: -0.27,
  INTP: 0.03,
  INFJ: 0.16,
  INTJ: 0.04,
  ISFP: 0.36,
  ISTP: -0.35,
  ISFJ: 0.34,
  ISTJ: 0.18,
  ENFP: 0.36,
  ENTP: 0.25,
  ESTJ: 0.43,
  ESFJ: 0.19,
  ESFP: 0.14,
  ENFJ: 0.08,
  ESTP: 0.07,
  ENTJ: 0.08,
}

export const PROFILE_BASELINE_STD: Readonly<Record<string, number>> = {
  INFP: 9.57,
  INTP: 10.89,
  INFJ: 6.25,
  INTJ: 5.83,
  ISFP: 8.68,
  ISTP: 7.92,
  ISFJ: 8.44,
  ISTJ: 7.74,
  ENFP: 4.80,
  ENTP: 5.89,
  ESTJ: 7.98,
  ESFJ: 11.45,
  ESFP: 7.19,
  ENFJ: 9.35,
  ESTP: 8.77,
  ENTJ: 8.02,
}

export function profileZScore(type: string, raw: number): number {
  const m = PROFILE_BASELINE_MEAN[type] ?? 0
  const s = PROFILE_BASELINE_STD[type] ?? 1
  return (raw - m) / s
}
