/**
 * ランダム回答1万人を流して各軸の baseline (mean / std) を算出。
 * src/lib/calibration.ts に書き出す。
 *
 * 用途:
 *   - determinePhase1Type / determinePhase3Type の z-score 比較
 *   - scoreMbti() の正規化
 */

import * as fs from "fs"
import * as path from "path"

import {
  phase1Questions,
  determinePhase1Type,
  determinePhase3Type,
} from "../src/lib/questions"
import { selectAdaptivePhase2, selectAdaptivePhase3 } from "../src/lib/adaptive"
import type { AnalysisScores, Question } from "../src/lib/types"

const N = 10000
const SEED = 7777

function makeRng(seed: number) {
  let s = seed >>> 0
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0
    return s / 0x100000000
  }
}

const rng = makeRng(SEED)

function applyChoice(scores: Record<string, number>, q: Question, idx: number) {
  const choice = q.choices[idx]
  for (const [k, v] of Object.entries(choice.scores)) {
    scores[k] = (scores[k] ?? 0) + (v ?? 0)
  }
}

function simulateOne(): Record<string, number> {
  const scores: Record<string, number> = {}

  for (const q of phase1Questions) {
    applyChoice(scores, q, Math.floor(rng() * q.choices.length))
  }
  const p1 = determinePhase1Type(scores as AnalysisScores)

  const phase2Qs = selectAdaptivePhase2(p1, scores as AnalysisScores)
  for (const q of phase2Qs) {
    applyChoice(scores, q, Math.floor(rng() * q.choices.length))
  }
  const p3 = determinePhase3Type(scores as AnalysisScores)

  const phase3Qs = selectAdaptivePhase3(p3, scores as AnalysisScores)
  for (const q of phase3Qs) {
    applyChoice(scores, q, Math.floor(rng() * q.choices.length))
  }

  return scores
}

const all: Record<string, number>[] = []
for (let i = 0; i < N; i++) all.push(simulateOne())

const allAxes = Array.from(
  all.reduce<Set<string>>((set, s) => {
    Object.keys(s).forEach((k) => set.add(k))
    return set
  }, new Set())
).sort()

function mean(xs: number[]) {
  return xs.reduce((a, b) => a + b, 0) / xs.length
}
function std(xs: number[]) {
  const m = mean(xs)
  return Math.sqrt(mean(xs.map((x) => (x - m) ** 2)))
}

const stats: Record<string, { mean: number; std: number }> = {}
for (const ax of allAxes) {
  const v = all.map((s) => s[ax] ?? 0)
  const m = mean(v)
  const sd = std(v)
  stats[ax] = { mean: Math.round(m * 100) / 100, std: Math.round(sd * 100) / 100 }
}

const lines: string[] = [
  "// AUTO-GENERATED by scripts/calibrate.ts",
  `// N=${N}, seed=${SEED}`,
  "// 各軸の \"ランダム回答時の平均/標準偏差\" を保存。z-score 化に使う。",
  "",
  "export const BASELINE_MEAN: Readonly<Record<string, number>> = {",
]
for (const ax of allAxes) {
  lines.push(`  ${ax}: ${stats[ax].mean.toFixed(2)},`)
}
lines.push("}")
lines.push("")
lines.push("export const BASELINE_STD: Readonly<Record<string, number>> = {")
for (const ax of allAxes) {
  lines.push(`  ${ax}: ${Math.max(stats[ax].std, 0.01).toFixed(2)},`)
}
lines.push("}")
lines.push("")
lines.push("// score を z-score 化（baseline 想定からの偏差）")
lines.push("export function zScore(axis: string, raw: number): number {")
lines.push("  const m = BASELINE_MEAN[axis] ?? 0")
lines.push("  const s = BASELINE_STD[axis] ?? 1")
lines.push("  return (raw - m) / s")
lines.push("}")
lines.push("")

const outPath = path.join(__dirname, "..", "src", "lib", "calibration.ts")
fs.writeFileSync(outPath, lines.join("\n"))
console.log(`Wrote ${outPath}`)
console.log(`Axes: ${allAxes.length}`)
console.log(`Sample stats: lowTempEmotion mean=${stats["lowTempEmotion"]?.mean} std=${stats["lowTempEmotion"]?.std}`)
